dotenv = require('dotenv');
dotenv.config();

const {GoogleGenAI} = require('@google/genai');
const ai = new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY})


const organizeNoteContent = async (rawText)=>{
    console.log(" Constructing prompt and contacting Gemini...");

    const prompt = `
    Tu es un assistant médical qui structure des notes cliniques.

        RÈGLES STRICTES :
        - N'invente et n'infère aucune information absente de la note. Si une section n'a pas d'information correspondante, écris exactement : "Non renseigné".
        - Ne reformule pas le sens clinique, uniquement le format.
        - Sortie en texte brut STRICT : aucun Markdown, aucun symbole **, #, -, *, aucune numérotation. Uniquement le nom de la section suivi de deux-points, puis le texte.

        FORMAT DE SORTIE (respecter exactement ces 6 en-têtes, dans cet ordre) :
        Motif de consultation:
        Symptômes
        Histoire de la maladie:
        Examen clinique:
        Diagnostic:
        Plan de traitement:
    `
    try{
    const response = await ai.models.generateContent({
        model : 'gemini-2.5-flash',
        contents : rawText,
        config:{
            systemInstruction : prompt,
            responseMimeType:'text/plain'
        }
    })  

    console.log("\n Response Received Successfully!");

    const generatedText = response.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!generatedText) {
        throw new Error("No text generated by Gemini");
    }
    return generatedText;
    }
    catch(err){
        console.error("Error while generating response :",err);
        throw new Error("Échec de l'appel à l'IA");
    }

}

const summarizeHistory = async (notes)=>{
    console.log(" Constructing prompt and contacting Gemini...");
    const notes_assembly = notes.map(note => {
       return `Date : ${note.date_creation} \nContenu : ${note.contenu_structure} `
    }).join('\n\n');
    const prompt = `  
        Tu es un assistant médical qui rédige des résumés de dossier patient.

                RÈGLES STRICTES :
                - Base-toi UNIQUEMENT sur les comptes rendus fournis ci-dessous. N'invente et n'infère aucune information absente.
                - Si les comptes rendus sont insuffisants pour dégager une tendance (ex: un seul motif isolé, pas de récurrence), ne force pas une conclusion — dis-le explicitement.
                - Reste factuel et concis. Pas d'interprétation clinique au-delà de ce qui est écrit.
                - Sortie en texte brut STRICT : aucun Markdown, aucun symbole **, #, -, *, aucune numérotation.

                FORMAT DE SORTIE (respecter exactement ces 4 en-têtes, dans cet ordre) :
                Motifs de consultation récurrents:
                Diagnostics:
                Traitements prescrits:
                Évolution de l'état du patient:

               
     `
     try{  
        const result = await ai.models.generateContent({
            model:'gemini-2.5-flash',
            contents: notes_assembly,
            config:{
                systemInstruction : prompt,
                responseMimeType:'text/plain'
            }
        })

        const generatedSummary = result.candidates?.[0]?.content?.parts?.[0]?.text;
        if(!generatedSummary){
            throw new Error("No text generated")
        }
        return generatedSummary;
    }
    catch(err){
        console.error("Erreur lors de la generation du résumé :",err);
        throw new Error("Echec de l'appel à l'IA");
    }
}

module.exports = {organizeNoteContent,summarizeHistory};